### ISSUE TITLE
关于标题栏的建议，

### ISSUE THREAD

**Issue by CYZZ** [12207480/TYPagerController#1]
首先下滑线最好和标题等宽，在滑动的过程中应该预估两个标题宽度的差距进行下划线长度动画显示，而不是先拉长再缩短，最好在滑动下边子控制器的时候让标题栏的动画保持和点击标题切换的动画一致（点击标题的时候（下划线几乎不动，标题栏滚动这种感觉和安卓原生的很像用户体验好些，），建议在标题栏的左右部分可以添加按钮：建议参考XTPageControl，他做的比较美观标题栏可以有多种样式：居左显示，居中显示，均分头部宽度功能，但是性能方面不是很好，如果考虑性能优化建议参考WMPageController，目前还是比较成熟的一个开源库。

**Comment by 12207480** [comment]
都可以设置 
![image](https://cloud.githubusercontent.com/assets/6346030/15536658/e5793940-22a4-11e6-992a-80cc2327d025.png)

**Comment by CYZZ** [comment]
最好每个属性和方法都用文档注释，这样在设置相关属性和调用方法的时候能够清晰的看到说明。

**Comment by 12207480** [comment]
恩 说的很对
