### ISSUE TITLE
设置的字数不同字号不同UI上差异比较大

### ISSUE THREAD

**Issue by AssassinMan** [12207480/TYPagerController#104]
正常设置的字号是14，最大是24  CGAffineTransformMakeScale 因为是用这个比例缩小的缘故，本身的cell大小不变。而内容变的很小。导致空白会非常多。 不知道怎样能动态缩小和放大。 想过自适应cell大小或者是在写一个layout。

**Comment by 12207480** [comment]
那样就没有变小动画

**Comment by AssassinMan** [comment]
我就是想都支持，又有动画，又可以缩进距离。有什么好的方案吗？
