### ISSUE TITLE
当PagerControllerDmeoController （第一个当前页面viewcontroller 放一个tableview ） 用于window.rootViewControlle 的时候  布局有问题 

### ISSUE THREAD

**Issue by LiGuanWen** [12207480/TYPagerController#105]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    self.window = [[UIWindow alloc]initWithFrame:[[UIScreen mainScreen] bounds]];
    PagerControllerDmeoController *vc = [[PagerControllerDmeoController alloc] init];
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];
    self.window.rootViewController = nav;
    [self.window makeKeyAndVisible];
    return YES;
}
当PagerControllerDmeoController （第一个当前页面viewcontroller 放一个tableview ） 用于window.rootViewControlle 的时候  布局有问题

**Comment by 12207480** [comment]
有demo吗

**Comment by LiGuanWen** [comment]
链接: https://pan.baidu.com/s/1LBYLF-o6C0EO49Gw_mw6Xg 密码: hds1
你好 我已经把demo上传到百度云了

**Comment by LiGuanWen** [comment]
@12207480

**Comment by LiGuanWen** [comment]
链接: https://pan.baidu.com/s/1LBYLF-o6C0EO49Gw_mw6Xg 密码: hds1
你好 我已经把demo 放到百度云了  你下载一下 然后直接运行 就可以发现 第一个页面 UI适配有问题 然后我改成用WMPageController 这个框架 就正常了。。 但是还是比较喜欢用你这个框架 希望能修复好

**Comment by 12207480** [comment]
已经修复了
