### ISSUE TITLE
怎么改变子控制器状态后，刷新数据

### ISSUE THREAD

**Issue by weizhangCoder** [12207480/TYPagerController#106]
改变滑动控制器的状态后，因为不太确定这个具体变为那个状态，所以怎么把所有的的子控制器的数据都请求一下，这个怎么弄比较好。

**Comment by 12207480** [comment]
不太懂你的意思

**Comment by weizhangCoder** [comment]
我描述的不太清楚，我详细在描述下，就是滑动pagerController中添加了好多控制器A，A控制器的cell中有订单的状态，一旦cell中订单的状态发生变化的时候，刷新当前控制器没有问题，但是他的状态变为别的状态了，怎么可以把别的状态的数据也刷新一下。

**Comment by 12207480** [comment]
但是他的状态变为别的状态了 什么意思？

**Comment by 12207480** [comment]
viewController 有 viewwillapper 每次将要出现的时候都会调用

**Comment by weizhangCoder** [comment]
恩，就是比较像订单，有待收货，已收货，被拒，已取消，这些状态，要是一个订单发生变化，肯定是要对应的2个控制器刷新数据才能展示最新的状态，要是把请求都写在viewvillapper 里面感觉每次都要请求，好像有点浪费，所以不知道你遇到这样的情况会怎么处理。感谢回复的这么及时。

**Comment by 12207480** [comment]
发送通知给其他控制器

**Comment by 12207480** [comment]
改变状态的时候 发送通知给其他控制器

**Comment by 12207480** [comment]
可以
