### ISSUE TITLE
横竖屏切换有问题  

### ISSUE THREAD

**Issue by qiuyubude** [12207480/TYPagerController#111]
在最后几个标签下 push进横屏在pop回来 回不到原先界面  会pop到别的标签下

**Comment by mengzhh** [comment]
您好横竖屏切换问题解决了吗？

**Comment by YangSugar** [comment]
我也遇到横竖屏切换问题，后来我把推出来横屏页面 强制旋转就解决了 估计是某些布局跟设备的方向有关
