### ISSUE TITLE
生命周期处理有问题

### ISSUE THREAD

**Issue by neobug** [12207480/TYPagerController#118]
点击PagerControllerDmeo，进入页面，切换不同的tab,之前已经加载过的CollectionViewController控制器会dealloc,再点tab切换回来就会走，viewdidload， 如果我数据请求是在viewdidload，那来回切换tab，就会重复去请求并刷新界面

**Comment by 12207480** [comment]
因为Controller是放到cache里，如果不想释放  可以设置 prefetchItemCount
