### ISSUE TITLE
展示的字体比设置的字体要小吧?

### ISSUE THREAD

**Issue by YanLYM** [12207480/TYPagerController#122]
![image](https://user-images.githubusercontent.com/28438058/46241898-35b00f00-c3f3-11e8-8392-26f1dad6d5f3.png)

_selectFontScale = self.normalTextFont.pointSize/(self.selectedTextFont ? self.selectedTextFont.pointSize:self.normalTextFont.pointSize);

**Comment by 12207480** [comment]
按比例缩小字体
