### ISSUE TITLE
tabbar 设置titleLabel字体 无论怎么设置都不会加粗，并且字体大小和正常不同，作者可以解释一下吗

### ISSUE THREAD

**Issue by wuxuezhen** [12207480/TYPagerController#125]

**Comment by wuxuezhen** [comment]
666，可以升级一下的




| |
xzzhenw
邮箱：xzzhenw@163.com
|

Signature is customized by Netease Mail Master

在2018年11月30日 14:26，yeBlueColor 写道：

是的无法加粗

**Comment by GeekZP** [comment]
> 666，可以升级一下的 | | xzzhenw 邮箱：xzzhenw@163.com | Signature is customized by Netease Mail Master 在2018年11月30日 14:26，yeBlueColor 写道： 是的无法加粗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这个有解决方案么

**Comment by wuxuezhen** [comment]
在修改库




| |
xzzhenw
邮箱：xzzhenw@163.com
|

Signature is customized by Netease Mail Master

在2019年01月19日 16:10，郑鹏 写道：

666，可以升级一下的 | | xzzhenw 邮箱：xzzhenw@163.com | Signature is customized by Netease Mail Master 在2018年11月30日 14:26，yeBlueColor 写道： 是的无法加粗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这个有解决方案么
