### ISSUE TITLE
TYPagerView如何刷新当前显示页面的数据

### ISSUE THREAD

**Issue by Xcode123456** [12207480/TYPagerController#127]
你好，我在使用TYPagerView的
- (UIView *)pagerView:(TYPagerView *)pagerView viewForIndex:(NSInteger)index prefetching:(BOOL)prefetching的方法中，我想要根据状态来判断显示的界面，具体的是当没有数据的时候显示空白页，当有数据的时候替换当前的页面，呈现有数据的界面。这是我想要使用这个达到的效果，但是我调用reloadData是都并没有实现我想要的效果，请问我是要设置什么属性吗？ 还是暂时不支持这个功能。期待您的回答谢谢。

**Comment by 12207480** [comment]
还不支持
