### ISSUE TITLE
progressColor改不了

### ISSUE THREAD

**Issue by GuessEver** [12207480/TYPagerController#14]
setProgressColor无效

**Comment by 12207480** [comment]
好的 我看看

**Comment by 12207480** [comment]
已更新

**Comment by GuessEver** [comment]
https://github.com/12207480/TYPagerController/blob/master/TYPagerControllerDemo/TYPagerController/TYTabButtonPagerController.m#L128
```
self.collectionViewBar.backgroundView = collectionViewBarColor;
```
应该是`backgroundColor`
