### ISSUE TITLE
第4行点进去的页面，如果只有两个tab的话，标题不能居中么？

### ISSUE THREAD

**Issue by hegelsu** [12207480/TYPagerController#17]
第4行点进去的页面，如果只有两个tab的话，标题不能居中么？

**Comment by 12207480** [comment]
可以 需要自己计算
![image](https://cloud.githubusercontent.com/assets/6346030/18296657/ba599ff8-74dd-11e6-8f1f-43f55d9ec557.png)

**Comment by hegelsu** [comment]
好的

**Comment by 12207480** [comment]
已更新添加字段
