### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by GaoDaobin** [12207480/TYPagerController#21]
![img_0419](https://cloud.githubusercontent.com/assets/8831690/20375955/98f3722c-acbd-11e6-9d85-1971b00ac724.PNG)
发现一个bug，dang当选中tab2，然后滑动到tab7并选中，在滑动惠tab2，此时tab2还是红色

**Comment by robinvpersie** [comment]
在CollectionView的代理里面再重新配置Cell的颜色和transform。自己加了一个代理方法
///////
-(void)collectionView:(UICollectionView *)collectionView willDisplayCell:(UICollectionViewCell *)cell forItemAtIndexPath:(NSIndexPath *)indexPath{
    
    TYTabTitleViewCell * displyacell = (TYTabTitleViewCell *)cell;
    [self.delegate pagerController:self configreDisplayCell:displyacell isCurrent:indexPath.item == self.curIndex? YES : NO atIndexPath:indexPath];
}

//////
-(void)pagerController:(TYTabPagerController *)pagerController configreDisplayCell:(UICollectionViewCell *)cell isCurrent:(BOOL)current atIndexPath:(NSIndexPath *)indexPath{
    TYTabTitleViewCell *titleCell = (TYTabTitleViewCell *)cell;
     if (current) {
         titleCell.titleLabel.textColor = self.selectedTextColor;
         titleCell.transform =  CGAffineTransformIdentity;
 }else {
        titleCell.transform = CGAffineTransformMakeScale(self.selectFontScale, self.selectFontScale);
        titleCell.titleLabel.textColor = self.normalTextColor;
    }

}

**Comment by 12207480** [comment]
已经解决
