### ISSUE TITLE
自定义cell

### ISSUE THREAD

**Issue by LargeShrimp** [12207480/TYPagerController#22]
如果实现自定义的cell ，一个UILable,一个UIImageView,我是继承与TYTabPagerController 还是TYPagerController 呢，谢谢

**Comment by 12207480** [comment]
继承TYTabPagerController 请查看TYTabButtonPagerController 实现

**Comment by LargeShrimp** [comment]
怎么根据数据源给imageView呢。数据源方法里只有一个给title 赋值的啊
