### ISSUE TITLE
翻页的时候-viewDidDisappear 不会调用

### ISSUE THREAD

**Issue by aelam** [12207480/TYPagerController#23]
翻页完成的时候消失的页面-viewDidDisappear 和出现的页面-viewDidAppear不会调用

**Comment by lvpengwei** [comment]
你可以自己补充：beginAppearanceTransition和endAppearanceTransition
https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html
·Managing Appearance Updates for Children·

**Comment by 12207480** [comment]
新版2.0已经支持
