### ISSUE TITLE
单词拼写 与建议

### ISSUE THREAD

**Issue by aelam** [12207480/TYPagerController#24]
*`isProgressScrollEnabel`  --> `isProgressScrollEnabled`
* reSize -> resize
* `TYPagerControllerDataSource`中 `- (NSInteger)numberOfControllersInPagerController;`应该加上PagerController
* `- (void)configurePropertys` --> `- (void)configureProperties`
*  #define kCollectionViewBarHieght 36 
    #define kUnderLineViewHeight 2 用静态常量
* `- (void)addUnderLineView` --> `- (void)addUnderlineView`
*

**Comment by aelam** [comment]
scrollView 的frame使用全屏, 但是contentInset 自动调整

**Comment by 12207480** [comment]
试试新版v2.0
