### ISSUE TITLE
TYTabPagerController tab  Not adjusted  below Navigation Bar.

### ISSUE THREAD

**Issue by vinodsupnekar** [12207480/TYPagerController#29]
Hi,
   I need to shift Tab view by around 60 pixel on Y axis.
I Need to place Navigation Bar above  Pager View.
  'contentTopEdging' not working as expected here.

![simulator screen shot may 18 2017 6 34 12 pm](https://cloud.githubusercontent.com/assets/4056720/26203391/9a90f60c-3bf8-11e7-9ec2-fceae09a09b8.png)

waiting for reply.

**Comment by 12207480** [comment]
I am afraid I can't help you

**Comment by vinodsupnekar** [comment]
That's really disappointing to me.
Did  you really got my issue, OR am i not clear in my question?
I need to know the reason of your inability to answer my question.

**Comment by 12207480** [comment]
thank you,this  is a bug, I will fix it,tomorrow

**Comment by 12207480** [comment]
add add property,you can set collectionViewBarOffsetY = 64;
