### ISSUE TITLE
切换动画、TYPagerControllerDelegate时机/次数

### ISSUE THREAD

**Issue by fightrain** [12207480/TYPagerController#3]
1.点击tab切换不支持pageViewController的动画切换。楼主是否会考虑增加该功能？scrollView的话可能要考虑维护三个页面（当前、左右），点击tab选项切换时用于动画显示。
2.TYPagerControllerDelegate中现有方法：- (void)pagerController:(TYPagerController *)pagerController transitionFromIndex:(NSInteger)formIndex toIndex:(NSInteger)toIndex progress:(CGFloat)progress;会在didScroll的时候多次调用，不适合做切换后的一些处理。是否考虑增加完成切换时的回调方法（只调用一次）。
TYPagerController功能已经很丰富，打算用起来。以上，只是使用您的TYPagerController时遇到的一些场景限制。希望框架越来越完善~

**Comment by 12207480** [comment]
第二个问题  这个方法 只会调用一次  - (void)pagerController:(TYTabPagerController *)pagerController transitionFromeCell:(UICollectionViewCell *)fromCell toCell:(UICollectionViewCell *)toCell animated:(BOOL)animated;

**Comment by fightrain** [comment]
谢谢回答。
第二个问题，在你的demo中打印不难发现，的确是调用了多次。
第一个问题，哈哈，我刚好有这个需求，所以有此一问。我打算按下面的思路写了个测试：移除不需要显示的View，或者将其设置透明，scrollView里只留三个View的空间，当前显示的view在中间，切换新View时临时将新View移动到其左右，至于生命周期可以通过childController的add/remove去管理。

**Comment by fightrain** [comment]
第二个问题，TYTabPagerController中加入打印，手动滑动试试看
- (void)transitionFromIndex:(NSInteger)fromIndex toIndex:(NSInteger)toIndex progress:(CGFloat)progress
{
    UICollectionViewCell *fromCell = [self cellForIndex:fromIndex];
    UICollectionViewCell *toCell = [self cellForIndex:toIndex];
    
    NSLog(@"%ld",(long)toIndex);
    
    if (_tabDelegateFlags.transitionFromeCellProgress) {
        [self.delegate pagerController:self transitionFromeCell:fromCell toCell:toCell progress:progress];
    }
    
    [self setUnderLineFrameWithfromIndex:fromIndex toIndex:toIndex progress:progress];
}

**Comment by 12207480** [comment]
每次到达这一页的时候都会调用

**Comment by 12207480** [comment]
方法不一样 一个 animated:(BOOL)animated  一个  progress:(CGFloat)progress
