### ISSUE TITLE
每次滑动 我需要知道滑动到哪个位置。

### ISSUE THREAD

**Issue by songguolin** [12207480/TYPagerController#30]
每次滑动 我需要知道滑动到哪个位置。我需要一个block 来知道每次滑动当前的currentIndex。
场景描述：nav右上角有功能按钮，在不同页面功能按钮不一样，需要改变。
如果是我对您的代码理解不够，请简单说一下解决方案。
谢谢！！

**Comment by 12207480** [comment]
试试新版v2.0
