### ISSUE TITLE
我使用TYPagerController 往右滑动 可以切换数据  但是往左再滑动回去就不能切换数据

### ISSUE THREAD

**Issue by bujieshi** [12207480/TYPagerController#32]
- (UIViewController *)pagerController:(TYPagerController *)pagerController controllerForIndex:(NSInteger)index
这个方法往左滑动 这个方法可以走 ，但是往右滑动这个方法就不走，我想知道这个是什么原因呢？

**Comment by 12207480** [comment]
会自动缓存controller 所以在滚回来的时候不需要获取新的controller

**Comment by bujieshi** [comment]
能不能获取到这个缓存的数据,这个缓存的数据我是要时时显示的！

**Comment by 12207480** [comment]
你可以在 viewwillappear 里改变数据吧

**Comment by 12207480** [comment]
试试新版v2.0
