### ISSUE TITLE
您好,为什么我只能pod1.0.2版本

### ISSUE THREAD

**Issue by yangshuo321** [12207480/TYPagerController#38]
-> TYPagerController (1.0.2)
   page scroll View controller,simple,high custom,and have tabBar styles.
   pod 'TYPagerController', '~> 1.0.2'
   - Homepage: https://github.com/12207480/TYPagerController
   - Source:   https://github.com/12207480/TYPagerController.git
   - Versions: 1.0.2, 1.0.0 [master repo]
(END)

**Comment by 12207480** [comment]
pod repo update
