### ISSUE TITLE
发现一个Bug

### ISSUE THREAD

**Issue by mgv5** [12207480/TYPagerController#39]
我用的是iPhone4S,系统8.1.2. 当tabBar滑动最后一个后,再次往右边滑动,tabbar会选中倒数第二个cell(正常情况应该选中最后一个),用的测试程序就是从这里下载的demo.

**Comment by 12207480** [comment]
恩 我看看

**Comment by 12207480** [comment]
请问有详细的步骤吗 或截图

**Comment by 12207480** [comment]
看了下是tabbar的问题

**Comment by 12207480** [comment]
已修复
