### ISSUE TITLE
切换childController时的性能问题

### ISSUE THREAD

**Issue by fightrain** [12207480/TYPagerController#4]
通过添加移除ChildController的方式调用page 子页面的生命周期方法，是有一定性能损耗的。可以用iphone4 ios7设备上尝试一下，有卡顿。我也没有更好的方案，不过生命周期对于很多场景来说还是很重要的。

**Comment by 12207480** [comment]
按道理 不会有什么影响 可惜我手上没有4 只有6 测试了 没有卡顿问题
