### ISSUE TITLE
传入参数为animate，但是实际动画参数直接使用了NO

### ISSUE THREAD

**Issue by Alex1989Wang** [12207480/TYPagerController#40]
https://github.com/12207480/TYPagerController/blob/f613d6f640ea7f4efb91abb7bb7e64215cd2a1e8/TYPagerControllerDemo/TYPagerController/TYPagerViewLayout.m#L265

是不是应该修改为：
[_scrollView setContentOffset:CGPointMake(index * CGRectGetWidth(_scrollView.frame),0) animated:animate];

**Comment by 12207480** [comment]
这个是故意设置成NO，因为 目标页面相隔很多页 如果用动画效果会不好

**Comment by Alex1989Wang** [comment]
如果这样的话，直接使用TYPagerViewLayout和TYPagerView，来调用这个接口就不会有动画哦

**Comment by 12207480** [comment]
是的

**Comment by pcjbird** [comment]
那能不能改成相隔超过一页在设成NO呢，这样相邻的两页切换效果貌似也不好啊！！！

**Comment by pcjbird** [comment]
[_scrollView setContentOffset:CGPointMake(index * CGRectGetWidth(_scrollView.frame),0) animated:labs(_curIndex - index) > 1 ? NO : animate];

**Comment by 12207480** [comment]
这个可以
