### ISSUE TITLE
在点击TYTabBar的某个选项无法动画切换TYPagerView问题。

### ISSUE THREAD

**Issue by teanfoo** [12207480/TYPagerController#42]
在点击TYTabBar的某个选项无法动画切换TYPagerView问题。
原因：TYPagerViewLayout.m line:265
`/**
 scroll to item at index
 */
- (void)scrollToItemAtIndex:(NSInteger)index animate:(BOOL)animate {
    if (index < 0 || index >= _countOfPagerItems) {
        return;
    }
    [self scrollViewWillScrollToView:_scrollView animate:animate];
    [_scrollView setContentOffset:CGPointMake(index * CGRectGetWidth(_scrollView.frame),0) animated:NO];// 应改为：animated: animate
    [self scrollViewDidScrollToView:_scrollView animate:animate];
}`

**Comment by 12207480** [comment]
https://github.com/12207480/TYPagerController/issues/40

**Comment by 12207480** [comment]
https://github.com/12207480/TYPagerController/issues/40

**Comment by teanfoo** [comment]
抱歉，没注意看。
