### ISSUE TITLE
可以实现下划线位于标题的上面么?

### ISSUE THREAD

**Issue by YanCeyMichael** [12207480/TYPagerController#45]
可以实现下划线位于标题的上面么?

**Comment by 12207480** [comment]
![image](https://user-images.githubusercontent.com/6346030/29779136-3819f1e4-8c44-11e7-9da9-19f68cddd054.png)
可以，这个属性是距离底部的垂直距离

**Comment by YanCeyMichael** [comment]
感谢您提供的优秀开源代码
