### ISSUE TITLE
怎么将下拉刷新如MJRefresh结合到PagerView上(不是PagerViewController)?

### ISSUE THREAD

**Issue by YanCeyMichael** [12207480/TYPagerController#46]
怎么将下拉刷新如MJRefresh结合到PagerView上(不是PagerViewController)?

我尝试用 scrollView作为一个父视图去承载整个PagerView,然后给scrollView加上MJRefresh,发现并不能实现
pagerView本身是否可以直接添加MJRefresh?

**Comment by 12207480** [comment]
可以，看我的这个demo https://github.com/12207480/LovePlayNews
