### ISSUE TITLE
自定义样式问题

### ISSUE THREAD

**Issue by ultimatevegance** [12207480/TYPagerController#47]
![screen shot 2017-08-31 at 22 05 26](https://user-images.githubusercontent.com/9568495/29927349-a96620ec-8e98-11e7-95ef-69080b8cb6ec.png)

你好 如何实现 分页视图 为图中的效果？ 在导航栏的最中间 ？

**Comment by 12207480** [comment]
设置cellWidth固定值 设置sectionInset.left right  =( pagerview's width - 2*cellWidth-cellSpacing)/2

**Comment by 12207480** [comment]
layout添加一个属性adjustContentCellsCenter 设置YES 将会自动居中，已更新

**Comment by ultimatevegance** [comment]
好的
