### ISSUE TITLE
为什么显式让 shouldAutomaticallyForwardAppearanceMethods 方法返回 NO？

### ISSUE THREAD

**Issue by MrSongzj** [12207480/TYPagerController#49]
这样会导致 从下一个界面 pop 回来（navigationBar）或者 从其他界面切换回来（tabBar）的时候子VC 就不会走它的 [viewWillAppear :] 回调了。因为有需求是需要每一次显示VC的view的时候都刷新一下数据。所以想请教一下标题的问题。

**Comment by 12207480** [comment]
重写shouldAutomaticallyForwardAppearanceMethods方法以return NO的方式规避添加/删除/切换的不合适的生命周期调用。并通过beginAppearanceTransition和endAppearanceTransition方法在合适时机管理生命周期

**Comment by 12207480** [comment]
可是我现在测试设置为YES 好像对childcontroller 也不会造成影响

**Comment by MrSongzj** [comment]
我也尝试过不重写 shouldAutomaticallyForwardAppearanceMethods 方法（系统默认返回YES）,但是没有发现有不合适的生命周期调用问题（或者说我测得不全）。

**Comment by 12207480** [comment]
恩 我准备提供个api选择是否用系统的，明天更新

**Comment by 12207480** [comment]
已经更新
