### ISSUE TITLE
设置了delegate以后 标签的title就不见了

### ISSUE THREAD

**Issue by iron93** [12207480/TYPagerController#50]
本身是一个viewController。

    [self addChildViewController:self.pagerController];
    [self.view addSubview:_pagerController.view];
    _pagerController.view.frame = self.view.bounds;
    _arrTitle = [[NSArray alloc]initWithObjects:@"最新",@"最热", nil];

        _pagerController = [[TYTabButtonPagerController alloc]init];
//        _pagerController.delegate = self;
        _pagerController.dataSource = self;
        _pagerController.adjustStatusBarHeight = YES;
        _pagerController.cellSpacing = 2*KScreeScasle;
        _pagerController.cellEdging = 10*KScreeScasle;
        _pagerController.cellWidth = 70*KScreeScasle;
        _pagerController.normalTextFont = [UIFont systemFontOfSize:15*KScreeScasle];
        _pagerController.selectedTextFont = [UIFont systemFontOfSize:15*KScreeScasle];
        _pagerController.barStyle = TYPagerBarStyleProgressBounceView;
        _pagerController.progressColor = UIColorFromRGB(0xfc3047);
        _pagerController.progressWidth = 40*KScreeScasle;
        _pagerController.selectedTextColor = UIColorFromRGB(0xfc3047);

**Comment by 12207480** [comment]
可以 看看TabPagerControllerDemoController.m demo

**Comment by iron93** [comment]
之前用的是1.0的版本 现在更新到2.0了 标题栏还是有问题 没选中的title的fontsize大小是0 选中的正常  动画是从没有变大到显示正常

**Comment by iron93** [comment]
再调用一次reloaddata好了  还有一个问题 能让控制器初始化的时候就切到某一个子控制器吗

**Comment by 12207480** [comment]
还没有
