### ISSUE TITLE
請教一下如何預先設定 scroll index

### ISSUE THREAD

**Issue by kicpang** [12207480/TYPagerController#53]
我在 viewDidLoad 裡面做 setupPagerController, 然後用[self.pagerController scrollToControllerAtIndex:self.selectedIndex animate:NO];
可是出來後仍然預設在page 0 , 請問大家是怎樣set的？

**Comment by kicpang** [comment]
試了在 viewWillAppear 時call
[self.pagerController scrollToControllerAtIndex:self.selectedIndex animate:NO];
可是仍然預設了顯示page 0 , 求指教

**Comment by 12207480** [comment]
先要reloadData 然后在scrollToControllerAtIndex:

**Comment by 12207480** [comment]
已经更新
