### ISSUE TITLE
遇到了复用问题

### ISSUE THREAD

**Issue by LifeForLove** [12207480/TYPagerController#55]
我用的这种方式[pagerView.layout dequeueReusableItemWithReuseIdentifier:identifier forIndex:index]
但我想每一页view对应一组数据,但是当我翻到第三页的时候 会复用第一页的数据
我的解决方式是
NSString *identifier=[NSString stringWithFormat:@"%ld",index];
[_pageView.layout registerClass:[UIView class] forItemWithReuseIdentifier:identifier];
[pagerView.layout dequeueReusableItemWithReuseIdentifier:identifier forIndex:index]
这两句放在了一起,问题是解决了,但是想请教下有没有更好的解决方式

**Comment by 12207480** [comment]
还是不太明白

**Comment by LifeForLove** [comment]
那我怎么把demo发给你

**Comment by 12207480** [comment]
这个就可以 压缩后直接拖进来

**Comment by LifeForLove** [comment]
[TYPagerController-master.zip](https://github.com/12207480/TYPagerController/files/1320426/TYPagerController-master.zip)
直接在你的PagerViewDemoController里面改的 ,在view 里面添加了 一个CollectionView, 第一次打开的时候,你会发现什么都没有,我写了一个延迟两秒加载数据,稍微等两秒就好了.  问题1 :当从tab0 滑到 tab2 的时候 你会发现 tab2 上面 复用了 tab0 的数据 ,要等两秒后刷新数据 才能正常显示 . 问题2 : tab0 向下滑动到最底部,  然后再横向切换tab页面 ,你会发现 当你滑动到tab2 的时候,tab2页面也是默认滚动到最底部的.

**Comment by 12207480** [comment]
![image](https://user-images.githubusercontent.com/6346030/30690140-c535d782-9ef5-11e7-9e77-50ffc85eb19d.png)
可以再这里把collectionview 的offset 设置成0

**Comment by LifeForLove** [comment]
你说的这种不能从根本上解决问题,不能记录偏移量,其实我的想法是,把MyCollectionView里collectionview的数据源方法放到PagerViewDmeoController 里,用字典保存偏移量,来实现,不过很麻烦, 还有一种解决方式 ,就是之前说的不用复用来解决. 再就是用你demo里面的PagerControllerDmeoController 来解决,问题就是,我可能要把 MyCollectionView 改成控制器. 想听下你的意见.

**Comment by 12207480** [comment]
不复用，不需要改成控制器 只要init view 返回就可以了

**Comment by LifeForLove** [comment]
我试过了 ,但是每次翻页都要重新加载

**Comment by LifeForLove** [comment]
我想实现那种效果,有点类似于,今日头条,停止翻页后再开始加载,每次加载都会缓存...不知道具体要怎么实现.

**Comment by 12207480** [comment]
pageView.layout.autoMemoryCache = YES;

**Comment by 12207480** [comment]
可行不

**Comment by LifeForLove** [comment]
稍微有点体验不好的地方是,每次翻页都要重新加载,我的方式是,每次创建不用的标示符,不让他复用,基本能满足我的需求.

**Comment by LifeForLove** [comment]
非常感谢你的demo啊 , 写的很棒
