### ISSUE TITLE
在iPhone X上面tabBar显示位置上移

### ISSUE THREAD

**Issue by GaoDaobin** [12207480/TYPagerController#56]
<img width="370" alt="shot" src="https://user-images.githubusercontent.com/8831690/30778646-c0a277e2-a10d-11e7-90f7-494a00a4180b.png">

**Comment by 12207480** [comment]
好的

**Comment by 12207480** [comment]
只是demo的问题，库本身没问题

**Comment by GaoDaobin** [comment]
那这个要怎么写呢，我用在自己的项目里也出现这种情况

**Comment by GaoDaobin** [comment]
用老版的TYPagerController设置下安全区就行了，但是新版设置安全区后会向下偏移很多

**Comment by 12207480** [comment]
有demo吗

**Comment by GaoDaobin** [comment]
这个是Demo，新版和老板都有，可以对比看下
[Demo.zip](https://github.com/12207480/TYPagerController/files/1327174/Demo.zip)

**Comment by 12207480** [comment]
已经修复

**Comment by GaoDaobin** [comment]
嗯嗯，多谢
