### ISSUE TITLE
横竖屏切换问题

### ISSUE THREAD

**Issue by mgv5** [12207480/TYPagerController#57]
push进一个横屏页面,pop回来后当前显示的页面不是push之前的页面

**Comment by 12207480** [comment]
测试了没有复现，你要demo吗

**Comment by mgv5** [comment]
有,你点第三个控制器,然后push,再pop回来,这时选中的控制器不是第三个
https://github.com/mgv5/TYPageDemo.git

**Comment by 12207480** [comment]
修复了 你试下
[TYPageDemo-master.zip](https://github.com/12207480/TYPagerController/files/1340456/TYPageDemo-master.zip)

**Comment by mgv5** [comment]
OK

**Comment by 12207480** [comment]
Fixed #57
