### ISSUE TITLE
需要滑动一下才有选中的效果

### ISSUE THREAD

**Issue by LanYanQin** [12207480/TYPagerController#58]
![image](https://user-images.githubusercontent.com/15378253/30959640-70f57a7c-a406-11e7-9b78-09c332f83b3c.png)
这是我的初始化，我用frame的形式布局也是这样，需要滑动一下才有选中的效果。
我添加了一个选中的效果发现那个红色下划线在屏幕外面。
![image](https://user-images.githubusercontent.com/15378253/30960136-b7d97a32-a407-11e7-9696-d3a42a6ef245.png)
![image](https://user-images.githubusercontent.com/15378253/30959683-89382eea-a406-11e7-8a55-c6a7beedc0dc.png)
![image](https://user-images.githubusercontent.com/15378253/30959693-8ed61434-a406-11e7-81b6-a3923ab38c53.png)

**Comment by LanYanQin** [comment]
![image](https://user-images.githubusercontent.com/15378253/30960016-6ab771a0-a407-11e7-887d-c5070b32bf8e.png)
有时还崩溃在这里。

**Comment by LanYanQin** [comment]
原来是我的标题数组在reloadData后面初始化出现了问题。

**Comment by 12207480** [comment]
没问题吧
