### ISSUE TITLE
点击上方title的时候颜色不会跟随改变.

### ISSUE THREAD

**Issue by ThePilgrimApp** [12207480/TYPagerController#6]
![qq20160615-0](https://cloud.githubusercontent.com/assets/17759369/16066269/68ce86ca-32e4-11e6-81d6-69c12b1b15c6.png)

**Comment by 12207480** [comment]
没有发现这个情况 哪里？

**Comment by ThePilgrimApp** [comment]
我测试的是可变 渐变1 带导航 pagerController / 可变 渐变2 带导航 pagerController 这两个demo.
发现问题:1.直接点击其中莫个title,底部页面切换,上方的title颜色不会跟随改变.
2.滚动下方视图,上方的title会出现多个高亮. 
还有github怎么添加图片给你看😂

**Comment by 12207480** [comment]
你的版本是最新的吗 ？  你修改了什么地方？
