### ISSUE TITLE
直接使用TYTabPagerController没办法接受tabbar item点击事件

### ISSUE THREAD

**Issue by bxyfighting** [12207480/TYPagerController#60]
需求：点击当前tabbar的item刷新列表
建议：把tabbar的delegate方法和pageview的delegate方法回调给TYTabPagerController的delegate

**Comment by 12207480** [comment]
发通知怎么样

**Comment by bxyfighting** [comment]
感觉应该统一

**Comment by 12207480** [comment]
建议：把tabbar的delegate方法和pageview的delegate方法回调给TYTabPagerController的delegate 啥意思  比如？

**Comment by bxyfighting** [comment]
比如TYTabPagerController中实现了TYTabPagerBarDelegate的pagerTabBar:didSelectItemAtIndex方法，但是TYTabPagerController的delegate不知道啊，我的建议是这样写：
TYTabPagerController.m
------------------------------------
- (void)pagerTabBar:(TYTabPagerBar *)pagerTabBar didSelectItemAtIndex:(NSInteger)index {
    [_pagerController scrollToControllerAtIndex:index animate:YES];
    if ([_delegate respondsToSelector:@selector(pagerTabBar: didSelectItemAtIndex:)]) {
        [_delegate pagerTabBar:self.tabBar didSelectItemAtIndex: index];
    }
}
其他delegate方法也一样

**Comment by 12207480** [comment]
可以

**Comment by 12207480** [comment]
已添加

**Comment by bxyfighting** [comment]
多谢，我这个比如太随意了，并没有很好的符合 点击‘当前’tabbar的item刷新列表的需求，还需要知道fromIndex，可否在加个tabPagerController:willSelectTabBarItemAtIndex或tabPagerController:shouldSelectTabBarItemAtIndex，这样在执行回调时，tabPagerController.pagerController.curIndex还是以前的值，就可以判断点击的是否是已选中的item。

**Comment by 12207480** [comment]
不会再做修改
