### ISSUE TITLE
麻烦您需要问下TYPagerController的问题

### ISSUE THREAD

**Issue by zhouhaokefd** [12207480/TYPagerController#62]
我的项目中使用啦TYPagerController和AsyncDisplayKit框架 TYPagerController中里面所有的子页面使用的ASViewController，ASViewController 里面放的是ASCollectionNode   ，好像TYPagerController在加载的时候一次是加载两个控制器。ASCollectionNode在固定的死数据的情况下滑动视图和显示数据正常。  ASCollectionNode但是在需要访问接口的时候，需要重新刷新ASCollectionNode [self.collectionNode reloadData];   第一个视图正常显示但是后面的视图就不正常显示啦(显示效果为空白页面)。。请问下这个问题是需要设置什么参数 还是需要怎么修改呢，麻烦您啦哈。谢谢

**Comment by 12207480** [comment]
https://github.com/12207480/LovePlayNews
可以看看这个
