### ISSUE TITLE
当设置

### ISSUE THREAD

**Issue by xiaohange** [12207480/TYPagerController#63]
1. 当设置self.tabBarHeight = 50;   self.tabBar.layout.adjustContentCellsCenter = YES;失效;

2. 当只需要两个item时, 如何居中, 均匀分布呢

**Comment by 12207480** [comment]
2.设置两个cell的宽度等view的宽度/2 即可

**Comment by 12207480** [comment]
1.已修复

**Comment by xiaohange** [comment]
@12207480 谢谢

**Comment by xiaohange** [comment]
@12207480 但是当设置两个的时候, 切换时item左右晃动

**Comment by xiaohange** [comment]
3,除了上面的这个问题, 还有一个就是希望能有一个参数控制是否需要放大效果

**Comment by 12207480** [comment]
什么设备 ios几，我这里没有发现晃动

**Comment by xiaohange** [comment]
@12207480 我的是iOS11 iphone7p, 当我设置2个按钮时, 切换时item会左右移动

**Comment by xiaohange** [comment]
![1](https://user-images.githubusercontent.com/14025157/32032314-0bb62cee-ba39-11e7-96c5-44a43c978ee6.gif)
左右会移动

**Comment by xiaohange** [comment]
@12207480

**Comment by 12207480** [comment]
我看看

**Comment by xiaohange** [comment]
@12207480 谢谢

**Comment by 12207480** [comment]
你这样三个等宽全屏不需要设置self.tabBar.layout.adjustContentCellsCenter = YES

**Comment by xiaohange** [comment]
我试了下不设置上面的属性也会出现晃动,

**Comment by 12207480** [comment]
把这个demo发给我

**Comment by xiaohange** [comment]
还是你的demo, 我只改了下item的个数和高度

**Comment by 12207480** [comment]
看看你改的地方

**Comment by xiaohange** [comment]
<img width="928" alt="9ceb6c29-9e9a-49ba-83e1-42aee98773e7" src="https://user-images.githubusercontent.com/14025157/32049489-c7f1871e-ba7f-11e7-9d6b-334a62a27066.png">
只改了这几个地方

**Comment by xiaohange** [comment]
@12207480

**Comment by 12207480** [comment]
好的

**Comment by 12207480** [comment]
self.tabBar.layout.cellSpacing = 0;
self.tabBar.layout.cellEdging = 0;
加上这两句即可

**Comment by xiaohange** [comment]
1. 这个item下滑线可以设置长度吗 2.是否有参数可控制item不使用文字动画效果,  @12207480 谢谢了, 辛苦了

**Comment by xiaohange** [comment]
![2017-10-28 10 45 34](https://user-images.githubusercontent.com/14025157/32130570-4b5ed518-bbcd-11e7-9b0f-75eccba1f3dd.png)

**Comment by 12207480** [comment]
1.progressEdging
2.normal select 设置一样的参数即可

**Comment by xiaohange** [comment]
解决了, 谢谢你, 没细心看参数,
