### ISSUE TITLE
self.navigationBar.translucent = NO; 时, 布局会向下偏移导航栏高度!

### ISSUE THREAD

**Issue by xiaohange** [12207480/TYPagerController#69]
self.navigationBar.translucent = NO;  这个如何适配呢? 有参数控制没

**Comment by 12207480** [comment]
@property (nonatomic, assign) CGFloat tabBarOrignY;
@property (nonatomic, assign) CGFloat tabBarHeight;

**Comment by xiaohange** [comment]
@12207480 谢谢
