### ISSUE TITLE
从子控制器中push一个新控制器然后在pop,子控制viewWillAppear不调用;

### ISSUE THREAD

**Issue by 1037390459** [12207480/TYPagerController#7]

**Comment by DaZuo** [comment]
我这块可以，估计是你的姿势不对。
倒是第一次进入`TYPagerController`时子控制器的`-viewWillAppear`不会调用，其他都会调用。看了下源码发现原因是添加添加子视图视图控制器是在`-viewWillLayoutSubviews`中，而这个方法是在`-viewWillAppear`调用之后再调用的，所以第一次没有调用。在`-viewDidLoad`中调用`[self.view layoutIfNeeded]`可解决。
@1037390459 @12207480

**Comment by 12207480** [comment]
恩 我去看看

**Comment by 12207480** [comment]
TYPagerController 添加
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    [self layoutContentViewIfNeed];
}

**Comment by 12207480** [comment]
已更新
