### ISSUE TITLE
如果item数量太少，tabbar位置异常

### ISSUE THREAD

**Issue by htmlios** [12207480/TYPagerController#72]
-------------------
|                 * * *       |
|                               |
|                               |
|                               |
|                               |
|                               |
-------------------

如果item数量太少，tabbar位置异常(如上所示)
位置偏右，不知道是否是bug

**Comment by 12207480** [comment]
没看懂图片

**Comment by htmlios** [comment]
![qq20171111-213622](https://user-images.githubusercontent.com/2826422/32689932-73a4549c-c728-11e7-9de3-f1cd1236843b.png)
如图

**Comment by htmlios** [comment]
![qq20171111-214035](https://user-images.githubusercontent.com/2826422/32691194-9c29af32-c73e-11e7-9e50-8157753681c8.png)
步骤：PagerViewDemo->update

**Comment by 12207480** [comment]
我看看
