### ISSUE TITLE
使用pageview的updateData方法，发现当前的page不会重新加载

### ISSUE THREAD

**Issue by pan817** [12207480/TYPagerController#75]
在TYPagerViewLayout的update方法，把可见的item去除后，setNeedLayout方法才会重建pageView
- (void)updateData {
    [self clearMemoryCache];
    [self removeVisibleItems];
    _countOfPagerItems = [_dataSource numberOfItemsInPagerViewLayout];
    [self setNeedLayout];
}

比较粗暴，麻烦看看这样改是否可以

**Comment by 12207480** [comment]
你可以reloaddata 然后 scrollToItemAtIndex

**Comment by pan817** [comment]
好的，我试试。谢谢！
