### ISSUE TITLE
bug: TYTabPagerController tab contentSize update

### ISSUE THREAD

**Issue by zhugexiaobo** [12207480/TYPagerController#77]
问题可以在 `TabPagerControllerDemoController` 中验证，横屏后恢复竖屏，`tabBar` 的 `contentSize` 没有恢复，还是横屏的 size。
应该是 `adjustContentCellsCenterInBar` 这个函数的问题。

**Comment by 12207480** [comment]
好的 我看看

**Comment by 12207480** [comment]
已修复
