### ISSUE TITLE
这个地方会随机crash

### ISSUE THREAD

**Issue by GaoDaobin** [12207480/TYPagerController#80]
当反复进入和返回一个集成了TYPager的控制器，会随机在某次进入的时候crash，我的这个控制器的tab是会动态改变的，不是固定不变的，crash的位置如下图
<img width="1141" alt="crash12" src="https://user-images.githubusercontent.com/8831690/34025973-de313ecc-e18d-11e7-88d6-79eff817dd87.png">

**Comment by GaoDaobin** [comment]
已经发现解决方法：第一次reloadData时必须至少创建一个tab，再动态改变tab就不会崩溃了

**Comment by chengxianghe** [comment]
> 已经发现解决方法：第一次reloadData时必须至少创建一个tab，再动态改变tab就不会崩溃了

你好，我也遇到这个问题了，不太确定你的描述，意思是如果数据为空的时候是不能调用reloadData么

**Comment by bolee** [comment]
目前我的解决了，做一下判断

**Comment by bolee** [comment]
我这里并不是随机崩溃，在iOS10，11一定崩溃，其他版本暂时没测到崩溃。
