### ISSUE TITLE
怎么样取消第一次进去预加载下一页 和 第一次进去不在第一个tab，在后面的tab？

### ISSUE THREAD

**Issue by aisielzuotian** [12207480/TYPagerController#83]
怎么样取消第一次进去预加载下一页 和 第一次进去不在第一个tab，在后面的tab？

**Comment by 12207480** [comment]
1.@property (nonatomic, assign) NSInteger prefetchItemCount;// preload left and right item's count , default 0

2.
[self reloadData];
[self scrollToControllerAtIndex:1 animate:YES];

**Comment by aisielzuotian** [comment]
你好，就是我想问一下，比如我里面有三个tab，外面也有这三个tab的入口，当我在外面点击了第二个tab的入口，进去后我只想直接加载第二个tab的下的页面内容，但是现在是会先加载第一个tab的内容，再加载后面的页面，我想问一下能从后面的入口进去而不加载第一页的内容吗？

**Comment by 12207480** [comment]
我看看

**Comment by aisielzuotian** [comment]
好的，谢谢

**Comment by 12207480** [comment]
已经更新！
    // only add controller at index 1
    [self scrollToControllerAtIndex:1 animate:YES];
    [self reloadData];
    
// first reloadData add controller at index 0,and scroll to index 1
    [self reloadData];
    [self scrollToControllerAtIndex:1 animate:YES];

**Comment by aisielzuotian** [comment]
你好，现在我在创建完成之后吊用这个偏移的方法        
 [self.pagerController scrollToControllerAtIndex:1 animate:YES];
 [self.pagerController reloadData];
这个代理方法会执行两次
- (UIViewController *)pagerController:(TYPagerController *)pagerController controllerForIndex:(NSInteger)index prefetching:(BOOL)prefetching
第一次 index=1   第二次index=0  然后进去之后tab停留在0 的那个tab

**Comment by 12207480** [comment]
不要使用pagerController.layout.prefetchItemCount = 1;

**Comment by aisielzuotian** [comment]
`- (void)viewDidLoad
{
    [super viewDidLoad];
    self.title = @"消息";

    [self addPagerController];
    [self addTopPageBar];
    [self loadTopPageBarData];

    [self.pagerController scrollToControllerAtIndex:self.messageNoticeType animate:YES];
    [self.pagerController reloadData];

}

- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];
    self.topPageBar.frame = CGRectMake(0, 0, SCREEN_WIDTH, 40);
    self.pagerController.view.frame = CGRectMake(0, 40.0, CGRectGetWidth(self.view.frame), SCREEN_HEIGHT- 64.0-40.0);
}

#pragma mark - 添加上面的分页控件
-(void)addTopPageBar
{
    //添加底部视图
    [self.view addSubview:self.topBarBottomView];
    
    TYTabPagerBar *tabBar = [[TYTabPagerBar alloc]init];
    tabBar.layout.barStyle = TYPagerBarStyleProgressView;
    tabBar.dataSource = self;
    tabBar.delegate = self;
    tabBar.layout.normalTextColor = [UIColor colorWithHexString:@"#666666"];
    tabBar.layout.selectedTextColor = [UIColor colorWithHexString:@"ff6700"];
    tabBar.layout.progressColor = [UIColor colorWithHexString:@"ff6700"];
    tabBar.layout.normalTextFont = [UIFont systemFontOfSize:15];
    tabBar.layout.selectedTextFont = [UIFont systemFontOfSize:15];
    tabBar.layout.cellWidth = SCREEN_WIDTH/3;
    tabBar.layout.cellSpacing = 0;
    tabBar.layout.cellEdging = 0;
    tabBar.layout.adjustContentCellsCenter = YES;
    [tabBar registerClass:[TYTabPagerBarCell class] forCellWithReuseIdentifier:[TYTabPagerBarCell cellIdentifier]];
    [self.view addSubview:tabBar];
    self.topPageBar = tabBar;
    
}
- (void)loadTopPageBarData {
    NSMutableArray *datas = [NSMutableArray array];
    NSArray *arr = @[@"PU公告",@"校园通知",@"系统通知"];
    for (NSInteger i = 0; i < arr.count; ++i) {
        [datas addObject:arr[i]];
    }
    self.datas = [datas copy];
    
    [self.topPageBar reloadData];
}

#pragma mark - TYTabPagerBarDelegate
- (CGFloat)pagerTabBar:(TYTabPagerBar *)pagerTabBar widthForItemAtIndex:(NSInteger)index {
    return  SCREEN_WIDTH / 3;
}

- (void)pagerTabBar:(TYTabPagerBar *)pagerTabBar didSelectItemAtIndex:(NSInteger)index
{
    [self.pagerController scrollToControllerAtIndex:index animate:YES];
}

#pragma mark ---------------------------
#pragma mark - 添加分页控制器
- (void)addPagerController
{
    TYPagerController *pagerController = [[TYPagerController alloc]init];
    pagerController.layout.prefetchItemCount = 0;
//    pagerController.layout.autoMemoryCache = NO;
    // 只有当scroll滚动动画停止时才加载pagerview，用于优化滚动时性能
    pagerController.layout.addVisibleItemOnlyWhenScrollAnimatedEnd = YES;
    pagerController.dataSource = self;
    pagerController.delegate = self;
    pagerController.scrollView.bounces = NO;
    [self addChildViewController:pagerController];
    [self.view addSubview:pagerController.view];
    _pagerController = pagerController;
}

#pragma mark -- TYPagerControllerDataSource
- (NSInteger)numberOfControllersInPagerController {
    return self.datas.count;
}

- (UIViewController *)pagerController:(TYPagerController *)pagerController controllerForIndex:(NSInteger)index prefetching:(BOOL)prefetching
{
    FWMessageNoticeView *messageVC = [[FWMessageNoticeView alloc]init];
    if (index==0)
    {
        messageVC.messageNoticeType = FWMessageNoticeType_PUNotice;
    }
    else if (index==1)
    {
        messageVC.messageNoticeType = FWMessageNoticeType_schoolNotice;
    }
    else
    {
        messageVC.messageNoticeType = FWMessageNoticeType_systemNotice;
    }
    return messageVC;
}

#pragma mark - TYTabPagerBarDataSource

- (NSInteger)numberOfItemsInPagerTabBar {
    return self.datas.count;
}

- (UICollectionViewCell<TYTabPagerBarCellProtocol> *)pagerTabBar:(TYTabPagerBar *)pagerTabBar cellForItemAtIndex:(NSInteger)index {
    UICollectionViewCell<TYTabPagerBarCellProtocol> *cell = [pagerTabBar dequeueReusableCellWithReuseIdentifier:[TYTabPagerBarCell cellIdentifier] forIndex:index];
    cell.titleLabel.text = self.datas[index];
    [cell configTabBadgeLabel:@"99"];
    return cell;
}

#pragma mark -- TYPagerControllerDelegate
- (void)pagerController:(TYPagerController *)pagerController transitionFromIndex:(NSInteger)fromIndex toIndex:(NSInteger)toIndex animated:(BOOL)animated
{
    [self.topPageBar scrollToItemFromIndex:fromIndex toIndex:toIndex animate:animated];
    
}

-(void)pagerController:(TYPagerController *)pagerController transitionFromIndex:(NSInteger)fromIndex toIndex:(NSInteger)toIndex progress:(CGFloat)progress
{
    [self.topPageBar scrollToItemFromIndex:fromIndex toIndex:toIndex progress:progress];
    
}
`    你好，我这边设置的是prefetchItemCount是0   但是这个代理方法还是会执行两次啊

**Comment by 12207480** [comment]
你可以看下 demo

**Comment by 12207480** [comment]
_addVisibleItemOnlyWhenScrollAnimatedEnd 设置为NO

**Comment by 12207480** [comment]
![image](https://user-images.githubusercontent.com/6346030/34596559-caf9f9e0-f21b-11e7-82c9-040800972b52.png)
PagerControllerDmeoController demo没问题

**Comment by aisielzuotian** [comment]
你好，我看了一下你的demo，你这边用的是继承于 TYTabPagerController 的这个类，我集成在我这边也是没问题的，但是我这边用的是继承于UIViewController的一个类，用到的TYTabPagerBar和TYPagerController，就相当于你demo里的PagerControllerDmeoController类，在这里面该如何实现这种效果呢？

**Comment by aisielzuotian** [comment]
已经好了，不知道是不是类的xcode的问题，怎么弄都弄不好，新建了一个类代码粘过来就好了，谢谢了，一个星。
