### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by GuoHongRui** [12207480/TYPagerController#86]
有四个控制器，导航栏添加一个按钮，按钮点击触发刷新事件，只有第一个控制器有tableView reloadDate 方法起作用，剩余的三个控制器tableView reloadDate方法失效，不刷新。

**Comment by 12207480** [comment]
剩余的三个控制器 创建了吗

**Comment by ApeCoderHR** [comment]
可以加你QQ或者teamViewer 远程吗。我现在的问题是viewDidLoad 重复执行两次
