### ISSUE TITLE
delegate无法响应

### ISSUE THREAD

**Issue by Zhengqi** [12207480/TYPagerController#9]
调试方法如下: NSLog断点设置在TYTabPagerController.m内
- (void)setDelegate:(id<TYTabPagerControllerDelegate>)delegate
{
    [super setDelegate:delegate];
    _tabDelegateFlags.didSelectAtIndexPath = [self.delegate respondsToSelector:@selector(pagerController:didSelectAtIndexPath:)];
    NSLog(@"_tabDelegateFlags.didSelectAtIndexPath: %d",_tabDelegateFlags.didSelectAtIndexPath);
}

会得到如下结果,导致delegate二次初始化后无法正确响应
2016-07-11 12:06:06.660 Pay@Table[18925:6885761] _tabDelegateFlags.didSelectAtIndexPath: 1
2016-07-11 12:06:06.661 Pay@Table[18925:6885761] _tabDelegateFlags.didSelectAtIndexPath: 0

**Comment by 12207480** [comment]
好的 我看看

**Comment by 12207480** [comment]
可以吧 demo发给我吗

**Comment by 12207480** [comment]
不太懂你的具体在操作

**Comment by Zhengqi** [comment]
把ViewController换成我这个试试~调试第三项
[ViewController.m.zip](https://github.com/12207480/TYPagerController/files/356491/ViewController.m.zip)

**Comment by 12207480** [comment]
我知道原因了

**Comment by 12207480** [comment]
你可以用继承

**Comment by 12207480** [comment]
好  我写个blcok 放出来

**Comment by 12207480** [comment]
已更新

**Comment by 12207480** [comment]
// didSelectIndexPath block
@property (nonatomic, copy) void (^didSelectIndexPathHandle)(NSIndexPath *indexPath);

**Comment by Zhengqi** [comment]
简单调试了下, 点击tab可以触发TYTabButtonPagerController里的block, 滑动tab无法触发, 
另外...由于在viewDidLoad里申明了delegate为self...所以其实除了继承你的class以外,didSelectAtIndexPath这个block我还是用不了

**Comment by Zhengqi** [comment]
改是改好了, 我把viewDidLoad里的delegate拿掉, 然后再自己的class里加了didSelectAtIndexPath和configreCell这两个方法...等我忙完了有机会仔细研究研究,感觉delegate申明这块还是需要完善的...

**Comment by nathanwhy** [comment]
didSelectIndexPathHandle 怎么没有了，delegate 除了继承还是没别的办法吗？

**Comment by Zhengqi** [comment]
已经解决了啊...不用继承也能用delegate

**Comment by nathanwhy** [comment]
你的第二个demo ， TYTabButtonPagerController 加了 delegate 就不能用了
