### ISSUE TITLE
分割不准的问题，如图

### ISSUE THREAD

**Issue by CH305426** [12207480/TYPagerController#92]
<img width="879" alt="2018-04-17 10 05 10" src="https://user-images.githubusercontent.com/13638807/38844631-eb19bafc-4226-11e8-8ba5-574fe1f2ca1a.png">
<img width="892" alt="2018-04-17 10 04 48" src="https://user-images.githubusercontent.com/13638807/38844635-ed9d980c-4226-11e8-933b-8e34468d044f.png">

设置的cellSpacing = 10，发现分割不均衡
改不动了，各方设置均无效，但是你demo上的好像九没出现这样

**Comment by CH305426** [comment]
已star，谢谢大佬

**Comment by 12207480** [comment]
应该不会出现这个情况
