### ISSUE TITLE
影响系统的滑动返回功能

### ISSUE THREAD

**Issue by yangda123** [12207480/TYPagerController#94]
滑动切换控制器的时候不会出现问题，但是滑动当前控制器，没有切换。会导致系统的滑动返回失效问题

**Comment by yangda123** [comment]
谢啦，解决了。与我自己重写的滑动返回手势冲突

**Comment by 12207480** [comment]
你是怎么解决的？

**Comment by yangda123** [comment]
我重写了系统返回事件，在父类中重新设置代理，加载在TYPageController子控制器继承父类，影响了滑动返回




| |
达仔
邮箱：18205598086@163.com
|

签名由 网易邮箱大师 定制

在2018年04月21日 18:39，yeBlueColor 写道：

你是怎么解决的？

**Comment by xiaohange** [comment]
自定义scrollview 继承UIScrollview . 判断拖动时候的偏移值self.contentOffset.x 。如果小于0 则让它返回 .  @yangda123 这个scrollview放在哪呢?
