### ISSUE TITLE
点击tabBar上的按钮，下面控制器会重复load，dealloc

### ISSUE THREAD

**Issue by YanLYM** [12207480/TYPagerController#95]
初次加载，通过左右滑动加载，控制器不会重复加载也不会dealloc；
但是如果不左右滑动，通过点击上面tabBar，控制器会重复创建，并且会dealloc；
点击tabBar里面调用[_pagerController scrollToControllerAtIndex:index animate:YES];
TYPagerControllerDelegate中transitionFromIndex的两个代理方法中处理tabBar滚动及选中调用的都是是
[_tabBar scrollToItemFromIndex:fromIndex toIndex:toIndex animate:animated];

![image](https://user-images.githubusercontent.com/28438058/39514491-e06c5c0e-4e29-11e8-90c2-37b497716f20.png)

**Comment by YanLYM** [comment]
demo里面也存在这个问题

**Comment by YanLYM** [comment]
prefetchItemCount不设置就可以了，这个属性什么时候需要用到呢，感觉提前加载这个属性会有问题

**Comment by 12207480** [comment]
提前加载  翻到下一页 无感知加载

**Comment by YanLYM** [comment]
PagerControllerDmeoController这个类
![image](https://user-images.githubusercontent.com/28438058/39561988-b1bc2558-4edb-11e8-8711-2cd847b46347.png)
这样写，初始化之后点击tabBar按钮切换控制器，会重复创建，释放
![image](https://user-images.githubusercontent.com/28438058/39562121-86bbee96-4edc-11e8-98be-c046c94ef4dd.png)

**Comment by Ctflemo** [comment]
prefetchItemCount 这个问题，如果有aVC，bVC，cVC三个控制器，一开始会加载aVC，bVC。这个时候如果从aVC滚动到bVC的时候bVC不会在重新加载，但是如果从aVC点击tab上的bVC，bVC会重新init return一次。 是否是因为滚动的代理跟点击的代理判断是否存在vc的时候不一致导致的.
